[tool.poetry]
name = "dezero"
version = "0.1.0"
description = "DeZero is a python package that provides a deep learing framework."
license = "MIT"
authors = [""]
maintainers = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.3"
